package View;

import Controller.DichVuController;
import DAO.DanhMucDichVuDAO;
import Model.DanhMucDichVu;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

public class QuanLiDichVuJPane extends javax.swing.JPanel {
    
    private ArrayList<DanhMucDichVu> listDichVu;
    DefaultTableModel tblDichVu;
    
    public QuanLiDichVuJPane() {
        initComponents();

        listDichVu = new DanhMucDichVuDAO().getListDichVu();
        
        tblDichVu = (DefaultTableModel) Table_DichVu.getModel();
        tblDichVu.setColumnIdentifiers(new Object[]{"STT", "Mã dịch vụ", "Tên dịch vụ", "Đơn giá"});

        showTableChiTietDV();
        Button_XoaDichVu.setEnabled(false);
        Button_SuaDichVu.setEnabled(false);

        Table_DichVu.setDefaultEditor(Object.class, null);
    }

    public void UpdateTable_DichVu() {
        tblDichVu.setRowCount(0);
        showTableChiTietDV();
    }
    public void showTableChiTietDV() {
        int i = 1;
        ArrayList<DanhMucDichVu> listDichVu = new DanhMucDichVuDAO().getListDichVu();
        for (DanhMucDichVu DichVu : listDichVu) {
            tblDichVu.addRow(new Object[]{i++, DichVu.getMaDV(), DichVu.getTenDV(), DichVu.getDonGia()});
        }
    }
    public DanhMucDichVu returnDichVu(int index) {
        int MaDichVu = (int) tblDichVu.getValueAt(index, 1);
        String TenDichVu = tblDichVu.getValueAt(index, 2).toString();
        int DonGia = Integer.parseInt(tblDichVu.getValueAt(index, 3).toString());

        return new DanhMucDichVu(MaDichVu, TenDichVu, DonGia);
    }
    public void clearJTextDichVu() {
        Text_MaDV.setText("");
        Text_TenDV.setText("");
        Text_DonGia.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Text_MaDV = new javax.swing.JTextField();
        Text_TenDV = new javax.swing.JTextField();
        Text_DonGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_DichVu = new javax.swing.JTable();
        Button_SuaDichVu = new javax.swing.JButton();
        Button_ThemDichVu = new javax.swing.JButton();
        Button_XoaDichVu = new javax.swing.JButton();
        Button_LamMoi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel5.setText("Tên dịch vụ");

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel6.setText("Mã dịch vụ");

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel7.setText("Đơn giá");

        Text_MaDV.setEditable(false);
        Text_MaDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Text_DonGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Table_DichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn giá"
            }
        ));
        Table_DichVu.setShowHorizontalLines(true);
        Table_DichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_DichVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_DichVu);

        Button_SuaDichVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_SuaDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconUpdateCustomer.png"))); // NOI18N
        Button_SuaDichVu.setText("Sửa");
        Button_SuaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SuaDichVuActionPerformed(evt);
            }
        });

        Button_ThemDichVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_ThemDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        Button_ThemDichVu.setText("Thêm");
        Button_ThemDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ThemDichVuActionPerformed(evt);
            }
        });

        Button_XoaDichVu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_XoaDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDelete.png"))); // NOI18N
        Button_XoaDichVu.setText("Xóa");
        Button_XoaDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaDichVuActionPerformed(evt);
            }
        });

        Button_LamMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_LamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        Button_LamMoi.setText("Tải lại");
        Button_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Text_MaDV)
                            .addComponent(Text_TenDV)
                            .addComponent(Text_DonGia, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Button_ThemDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_SuaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Button_XoaDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Button_LamMoi))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Text_MaDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Text_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Text_DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_XoaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_ThemDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_SuaDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("Chi tiết dịch vụ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ThemDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ThemDichVuActionPerformed
        if (new DichVuController().checkJtextDichVu(Text_TenDV, Text_DonGia)) {
            DanhMucDichVu DichVu = new DanhMucDichVu();
            DichVu.setTenDV(Text_TenDV.getText());
            DichVu.setDonGia(Integer.parseInt(Text_DonGia.getText()));
            if (new DanhMucDichVuDAO().ThemTTDichVu(DichVu)) {
                JOptionPane.showMessageDialog(this, "Thêm thành công.");
                listDichVu.add(DichVu);
                clearJTextDichVu();
                UpdateTable_DichVu();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            }
        }
    }//GEN-LAST:event_Button_ThemDichVuActionPerformed

    private void Button_XoaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaDichVuActionPerformed
        int indexTB = Table_DichVu.getSelectedRow();
        DanhMucDichVu DichVu = returnDichVu(indexTB);
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa dữ liệu?", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            if (indexTB < tblDichVu.getRowCount() && indexTB >= 0) {
                if (new DanhMucDichVuDAO().XoaTTDichVu(DichVu)) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    tblDichVu.removeRow(indexTB);
                    clearJTextDichVu();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại.");
                }
            }
        }
    }//GEN-LAST:event_Button_XoaDichVuActionPerformed

    private void Button_SuaDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SuaDichVuActionPerformed
        if (new DichVuController().checkJtextDichVu(Text_TenDV, Text_DonGia)) {
            int indexTB = Table_DichVu.getSelectedRow();

            int MaDV = Integer.parseInt(Text_MaDV.getText());
            String TenDV = Text_TenDV.getText();
            int DonGia = Integer.parseInt(Text_DonGia.getText());

            DanhMucDichVu DichVu = new DanhMucDichVu(MaDV, TenDV, DonGia);
            int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn sửa dữ liệu?", "Sửa dữ liệu", JOptionPane.YES_NO_OPTION);
            if (ret == JOptionPane.YES_OPTION) {
                if (new DanhMucDichVuDAO().SuaTTDichVu(DichVu)) {
                    if (indexTB < tblDichVu.getRowCount() && indexTB >= 0) {
                        tblDichVu.setValueAt(Text_TenDV.getText(), indexTB, 2);
                        tblDichVu.setValueAt(Text_DonGia.getText(), indexTB, 3);
                        JOptionPane.showMessageDialog(this, "Sửa thành công.");
                        clearJTextDichVu();
                    } else {
                        JOptionPane.showMessageDialog(this, "Sửa thất bại.");
                    }
                }
            }
        }
    }//GEN-LAST:event_Button_SuaDichVuActionPerformed

    private void Button_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LamMoiActionPerformed
        clearJTextDichVu();
        Button_ThemDichVu.setEnabled(true);
        Button_XoaDichVu.setEnabled(false);
        Button_SuaDichVu.setEnabled(false);
    }//GEN-LAST:event_Button_LamMoiActionPerformed

    private void Table_DichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_DichVuMouseClicked
        ListSelectionModel listTable_DichVu = Table_DichVu.getSelectionModel();
        listTable_DichVu.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Button_ThemDichVu.setEnabled(false);
        Button_XoaDichVu.setEnabled(true);
        Button_SuaDichVu.setEnabled(true);
        int indexTB = Table_DichVu.getSelectedRow();
        if (indexTB < tblDichVu.getRowCount() && indexTB >= 0) {
            Text_MaDV.setText(tblDichVu.getValueAt(indexTB, 1).toString());
            Text_TenDV.setText(tblDichVu.getValueAt(indexTB, 2).toString());
            Text_DonGia.setText(tblDichVu.getValueAt(indexTB, 3).toString());
        }
    }//GEN-LAST:event_Table_DichVuMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_LamMoi;
    private javax.swing.JButton Button_SuaDichVu;
    private javax.swing.JButton Button_ThemDichVu;
    private javax.swing.JButton Button_XoaDichVu;
    private javax.swing.JTable Table_DichVu;
    private javax.swing.JTextField Text_DonGia;
    private javax.swing.JTextField Text_MaDV;
    private javax.swing.JTextField Text_TenDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
