package View;

import Controller.DichVuController;
import DAO.ThongTinPhongDAO;
import DAO.DanhMucDichVuDAO;
import DAO.DataBaseConnection;
import DAO.HoaDonDichVuDAO;
import Model.ThongTinPhong;
import Model.DanhMucDichVu;
import Model.HoaDonDichVu;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class ThemDonDichVuJPane extends javax.swing.JPanel {

    private ArrayList<DanhMucDichVu> listDichVu;
    public HashMap<String, DanhMucDichVu> dsDichVu;
    private ArrayList<HoaDonDichVu> listDVPhong;
    DefaultTableModel tblDichVu, tbleDichVuPhong;
    Date date = new Date();

    public ThemDonDichVuJPane() {
        initComponents();

        dsDichVu = new HashMap<String, DanhMucDichVu>();
        listDichVu = new DanhMucDichVuDAO().getListDichVu();

        tbleDichVuPhong = (DefaultTableModel) Table_DichVuPhong.getModel();
        tbleDichVuPhong.setColumnIdentifiers(new Object[]{"STT", "Tên DV", "Ngày SD", "Số lượng", "Đơn giá", "Thành tiền"});

        showTableChiTietDV();
        showComboBox_MaPhg();
        showComboBox_TenDV();

        getDonGiaDV();
        Table_DichVuPhong.setDefaultEditor(Object.class, null);
    }

    public void showTableChiTietDV() {
        int i = 1;
        ArrayList<DanhMucDichVu> listDichVu = new DanhMucDichVuDAO().getListDichVu();
        for (DanhMucDichVu DichVu : listDichVu) {
            dsDichVu.put(DichVu.getTenDV(), DichVu);
        }
    }

    public void showComboBox_MaPhg() {
        ArrayList<ThongTinPhong> ttMaPhg = new ThongTinPhongDAO().getListPhongDangSD();
        for (ThongTinPhong data : ttMaPhg) {
            ComboBox_MaPhg.addItem(data.getMaPhg());
        }
    }

    public void showComboBox_TenDV() {
        ArrayList<DanhMucDichVu> ttTenDV = new DanhMucDichVuDAO().getListTenDV();
        for (DanhMucDichVu data : ttTenDV) {
            ComboBox_TenDV.addItem(data.getTenDV());
        }
    }

    public void getDonGiaDV() {
        int Gia = new DanhMucDichVuDAO().getGiaDV(ComboBox_TenDV.getSelectedItem().toString());
        Text_ThanhTien.setText(String.valueOf((int) Spinner_SoLuong.getValue() * Gia));
    }

    public void showTableDichVuPhong(String MaPhong) {
        int i = 1;
        listDVPhong = new HoaDonDichVuDAO().getListChiTietHDDV(MaPhong);
        for (HoaDonDichVu data : listDVPhong) {
            tbleDichVuPhong.addRow(new Object[]{i++, data.getTenDV(), data.getNgaySD(), data.getSoLuong(), data.getDonGia(), data.getSoLuong() * data.getDonGia()});
        }
    }

    public void UpdateTableDVPhong(String MaPhong) {
        tbleDichVuPhong.setRowCount(0);
        this.showTableDichVuPhong(MaPhong);
    }

    public void clearTextDVPhong() {
        Spinner_SoLuong.setValue(1);
        ComboBox_TenDV.setSelectedIndex(0);
    }

    public void viewReport(String fileName, HashMap para) {
        try {
            JasperDesign jasperDesign = JRXmlLoader.load(fileName);
            JasperReport jreReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jreReport, para, DataBaseConnection.getConnection());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Spinner_SoLuong = new javax.swing.JSpinner();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table_DichVuPhong = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_TenDV = new javax.swing.JComboBox<>();
        ComboBox_MaPhg = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        Text_ThanhTien = new javax.swing.JTextField();
        JDateChooser_NgaySuDung = new com.toedter.calendar.JDateChooser();
        Button_InHoaDon = new javax.swing.JButton();
        Button_XoaDVPhong = new javax.swing.JButton();
        Button_ThemDVPhong = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153), null, null));

        jLabel21.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel21.setText("Tên dịch vụ");

        jLabel22.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel22.setText("Số lượng");

        jLabel23.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel23.setText("Ngày sử dụng");

        Spinner_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Spinner_SoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 0, 50, 1));
        Spinner_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Spinner_SoLuongStateChanged(evt);
            }
        });

        Table_DichVuPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên DV", "Ngày SD", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        Table_DichVuPhong.setShowGrid(false);
        Table_DichVuPhong.setShowHorizontalLines(true);
        jScrollPane4.setViewportView(Table_DichVuPhong);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel3.setText("Mã phòng");

        ComboBox_TenDV.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_TenDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_TenDVActionPerformed(evt);
            }
        });

        ComboBox_MaPhg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ComboBox_MaPhg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_MaPhgActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        jLabel24.setText("Thành tiền");

        Text_ThanhTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JDateChooser_NgaySuDung.setDate(date);
        JDateChooser_NgaySuDung.setDateFormatString("dd-MM-yyyy");

        Button_InHoaDon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_InHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconBill.png"))); // NOI18N
        Button_InHoaDon.setText("In");
        Button_InHoaDon.setToolTipText("");
        Button_InHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_InHoaDonActionPerformed(evt);
            }
        });

        Button_XoaDVPhong.setFont(new java.awt.Font("Segoe UI Variable", 0, 14)); // NOI18N
        Button_XoaDVPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconDelete.png"))); // NOI18N
        Button_XoaDVPhong.setText("Xóa");
        Button_XoaDVPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_XoaDVPhongActionPerformed(evt);
            }
        });

        Button_ThemDVPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Button_ThemDVPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        Button_ThemDVPhong.setText("Thêm");
        Button_ThemDVPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ThemDVPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JDateChooser_NgaySuDung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBox_TenDV, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Spinner_SoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_MaPhg, 0, 166, Short.MAX_VALUE)
                            .addComponent(Text_ThanhTien))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_XoaDVPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(Button_ThemDVPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 397, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ComboBox_MaPhg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(ComboBox_TenDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(Spinner_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(JDateChooser_NgaySuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(Text_ThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_ThemDVPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_InHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_XoaDVPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("Dịch vụ phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_InHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_InHoaDonActionPerformed
        String maphg = ComboBox_MaPhg.getSelectedItem().toString();
        HashMap para = new HashMap();
        para.put("maphg", maphg);
        viewReport("src\\Reports\\HoaDonDV.jrxml", para);
    }//GEN-LAST:event_Button_InHoaDonActionPerformed

    private void Button_ThemDVPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ThemDVPhongActionPerformed
        HoaDonDichVu HDDV = new HoaDonDichVu();
        HDDV.setMaPHG(ComboBox_MaPhg.getSelectedItem().toString());
        HDDV.setTenDV(ComboBox_TenDV.getSelectedItem().toString());
        HDDV.setSoLuong((int) Spinner_SoLuong.getValue());
        HDDV.setNgaySD(JDateChooser_NgaySuDung.getDate());
        if (new HoaDonDichVuDAO().ThemDichVuPhong(HDDV, dsDichVu.get(HDDV.getTenDV()).getMaDV())) {
            JOptionPane.showMessageDialog(this, "Thêm thành công.");
            UpdateTableDVPhong(ComboBox_MaPhg.getSelectedItem().toString());
        } else {
            JOptionPane.showMessageDialog(this, "Thêm thất bại.");
            clearTextDVPhong();
        }
    }//GEN-LAST:event_Button_ThemDVPhongActionPerformed

    private void Button_XoaDVPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_XoaDVPhongActionPerformed
        int indexTB = Table_DichVuPhong.getSelectedRow();
        if (indexTB < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn dịch vụ để xóa.\nVui lòng chọn một dịch vụ trong bảng để xóa.");
            return;
        }
        HoaDonDichVu hddv = new HoaDonDichVu();
        hddv.setMaPHG(ComboBox_MaPhg.getSelectedItem().toString());
        DanhMucDichVu dv = dsDichVu.get(tbleDichVuPhong.getValueAt(indexTB, 1).toString());
        int ret = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa dữ liệu?", "Xóa dữ liệu", JOptionPane.YES_NO_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            if (indexTB < tbleDichVuPhong.getRowCount() && indexTB >= 0) {
                if (new HoaDonDichVuDAO().XoaDichVuPhong(hddv, dv.getMaDV())) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công.");
                    tbleDichVuPhong.removeRow((indexTB));
                    clearTextDVPhong();
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại.");
                }
            }
        }
    }//GEN-LAST:event_Button_XoaDVPhongActionPerformed

    private void ComboBox_MaPhgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_MaPhgActionPerformed
        UpdateTableDVPhong(ComboBox_MaPhg.getSelectedItem().toString());
    }//GEN-LAST:event_ComboBox_MaPhgActionPerformed

    private void ComboBox_TenDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_TenDVActionPerformed
        Spinner_SoLuong.setValue(1);
        getDonGiaDV();
    }//GEN-LAST:event_ComboBox_TenDVActionPerformed

    private void Spinner_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Spinner_SoLuongStateChanged
        getDonGiaDV();
    }//GEN-LAST:event_Spinner_SoLuongStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_InHoaDon;
    private javax.swing.JButton Button_ThemDVPhong;
    private javax.swing.JButton Button_XoaDVPhong;
    private javax.swing.JComboBox<String> ComboBox_MaPhg;
    public javax.swing.JComboBox<String> ComboBox_TenDV;
    private com.toedter.calendar.JDateChooser JDateChooser_NgaySuDung;
    public javax.swing.JSpinner Spinner_SoLuong;
    private javax.swing.JTable Table_DichVuPhong;
    public javax.swing.JTextField Text_ThanhTien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
