package View;

import DAO.DataBaseConnection;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JYearChooser;
import java.awt.Button;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class ThongKeJPane extends javax.swing.JPanel {

    public ThongKeJPane() {
        initComponents();
    }
    public void viewReport(String fileName, HashMap para) {
        try {
            JasperDesign jasperDesign = JRXmlLoader.load(fileName);
            JasperReport jreReport = JasperCompileManager.compileReport(jasperDesign);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jreReport, para, DataBaseConnection.getConnection());
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    
    public void viewReportSR(String fileName, String fileNameSR, HashMap para) {
        try {
            JasperDesign jasperDesign = JRXmlLoader.load(fileName);
            JasperDesign jasperDesignSR = JRXmlLoader.load(fileNameSR);

            JasperReport jreReport = JasperCompileManager.compileReport(jasperDesign);
            JasperReport jasperReportSR = JasperCompileManager.compileReport(jasperDesignSR);
            
            para.put("SubReportParam", jasperReportSR);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(jreReport, para, DataBaseConnection.getConnection());
            
            JasperViewer jv = new JasperViewer(jasperPrint, false);
            jv.setVisible(true);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Button_TKSLDatDV = new javax.swing.JButton();
        Button_TKSLDatPhong = new javax.swing.JButton();
        Button_TKDoanhThuThang = new javax.swing.JButton();
        Button_TKDoanhThuNam = new javax.swing.JButton();
        Button_HoaDonThanhToan = new javax.swing.JButton();

        Button_TKSLDatDV.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Button_TKSLDatDV.setText("Thống kê số lần đặt dịch vụ ");
        Button_TKSLDatDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKSLDatDVActionPerformed(evt);
            }
        });

        Button_TKSLDatPhong.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Button_TKSLDatPhong.setText("Thống kê số lượng đặt phòng");
        Button_TKSLDatPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKSLDatPhongActionPerformed(evt);
            }
        });

        Button_TKDoanhThuThang.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Button_TKDoanhThuThang.setText("Thống kê doanh thu theo tháng ");
        Button_TKDoanhThuThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKDoanhThuThangActionPerformed(evt);
            }
        });

        Button_TKDoanhThuNam.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Button_TKDoanhThuNam.setText("Thống kê doanh thu trong một năm ");
        Button_TKDoanhThuNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TKDoanhThuNamActionPerformed(evt);
            }
        });

        Button_HoaDonThanhToan.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        Button_HoaDonThanhToan.setText("Hóa đơn thanh toán");
        Button_HoaDonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_HoaDonThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_HoaDonThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(Button_TKDoanhThuNam, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                    .addComponent(Button_TKDoanhThuThang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_TKSLDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TKSLDatDV, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_TKDoanhThuThang, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_TKSLDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_TKDoanhThuNam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Button_TKSLDatDV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(Button_HoaDonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_TKSLDatDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKSLDatDVActionPerformed
        viewReport("src\\Reports\\ThongKeDichVu.jrxml", null);
    }//GEN-LAST:event_Button_TKSLDatDVActionPerformed

    private void Button_TKDoanhThuThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKDoanhThuThangActionPerformed
        JPanel pan = new JPanel();
        pan.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        JLabel Label_Thang = new JLabel("Chọn tháng ");
        pan.add(Label_Thang, gbc);
        gbc.gridx = 1;
        gbc.gridy = 0;
        JMonthChooser Thang = new JMonthChooser();
        pan.add(Thang, gbc);
        gbc.gridx = 0;
        gbc.gridy = 1;
        JLabel Label_Nam = new JLabel("Chọn năm ");
        pan.add(Label_Nam, gbc);
        gbc.gridx = 1;
        gbc.gridy = 1;
        JYearChooser Nam = new JYearChooser();
        pan.add(Nam, gbc);
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        Button bt_OK = new Button("OK");
        pan.add(bt_OK, gbc);
        JDialog jd = new JDialog();
        jd.setTitle("Lựa chọn");
        jd.setSize(200, 150);
        jd.add(pan);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        bt_OK.setActionCommand("OK");
        bt_OK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ("OK".equals(e.getActionCommand())) {
                    BigDecimal thang = new BigDecimal(Thang.getMonth() + 1);
                    BigDecimal nam = new BigDecimal(Nam.getYear());
                    HashMap para = new HashMap();
                    para.put("thang", thang);
                    para.put("nam", nam);
                    viewReportSR("src\\Reports\\DoanhThuTheoThang.jrxml", "src\\Reports\\subreportThongKeTheoThang_DV.jrxml", para);
                    jd.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_Button_TKDoanhThuThangActionPerformed

    private void Button_TKDoanhThuNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKDoanhThuNamActionPerformed
        JPanel pan = new JPanel();
        pan.setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.gridx = 0;
        gbc.gridy = 0;
        JLabel Label_Nam = new JLabel("Chọn năm ");
        pan.add(Label_Nam, gbc);
        gbc.gridx = 1;
        gbc.gridy = 0;
        JYearChooser Nam = new JYearChooser();
        pan.add(Nam, gbc);
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        Button bt_OK = new Button("OK");
        pan.add(bt_OK, gbc);
        JDialog jd = new JDialog();
        jd.setTitle("Lựa chọn");
        jd.setSize(200, 150);
        jd.add(pan);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        bt_OK.setActionCommand("OK");
        bt_OK.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ("OK".equals(e.getActionCommand())) {
                    BigDecimal nam = new BigDecimal(Nam.getYear());
                    HashMap para = new HashMap();
                    para.put("nam", nam);
                    viewReport("src\\Reports\\DoanhThuMotNam.jrxml", para);
                    jd.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_Button_TKDoanhThuNamActionPerformed

    private void Button_TKSLDatPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TKSLDatPhongActionPerformed
        HashMap para = new HashMap();
        viewReportSR("src\\Reports\\ThongKeSoLuongDatPhong.jrxml", "src\\Reports\\SoLanDatPhongCuaKH.jrxml", para);
    }//GEN-LAST:event_Button_TKSLDatPhongActionPerformed

    private void Button_HoaDonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_HoaDonThanhToanActionPerformed
        BigDecimal matt;
        HashMap para = new HashMap();
        try {
            String str = JOptionPane.showInputDialog(null, "Nhập vào mã thanh toán (Số nguyên)");
            matt = new BigDecimal(str);
            para.put("matt", matt);
            viewReportSR("src\\Reports\\HoaDonThanhToan.jrxml", "src\\Reports\\subreportDichVu.jrxml", para);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bạn phải nhập vào số nguyên!");
        }
    }//GEN-LAST:event_Button_HoaDonThanhToanActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_HoaDonThanhToan;
    private javax.swing.JButton Button_TKDoanhThuNam;
    private javax.swing.JButton Button_TKDoanhThuThang;
    private javax.swing.JButton Button_TKSLDatDV;
    private javax.swing.JButton Button_TKSLDatPhong;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
